services:
  postgres12:
    networks:
      - default
    image: postgres:12
    ports:
      - "${POSTGRES12_PORT:-5423}:5432" # use a non-standard port here
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-super-secret}
  postgres13:
    networks:
      - default
    image: postgres:13
    ports:
      - "${POSTGRES13_PORT:-5424}:5432" # use a non-standard port here
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-super-secret}
  postgres14:
    networks:
      - default
    image: postgres:14
    ports:
      - "${POSTGRES14_PORT:-5425}:5432" # use a non-standard port here
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-super-secret}
  postgres15:
    networks:
      - default
    image: postgres:15
    ports:
      - "${POSTGRES15_PORT:-5426}:5432" # use a non-standard port here
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-super-secret}
  postgres16:
    networks:
      - default
    image: postgres:16
    ports:
      - "${POSTGRES16_PORT:-5427}:5432" # use a non-standard port here
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-super-secret}
networks:
  default:
    driver: bridge
